"""fixed username field

Revision ID: 354aa9dbe22a
Revises: f3404894865b
Create Date: 2024-09-25 11:35:30.999878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354aa9dbe22a'
down_revision = 'f3404894865b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
